AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile

# Allow *VALID_CONFIG_KEYS.keys
Lint/AmbiguousOperator:
  Enabled: false

# This cop conflicts with other cops
Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 30

Metrics/ParameterLists:
  Enabled: false
